### PR TITLE
Fix operator precedence warnings, add support for HypreParVector expr templates

### LINKED ISSUE #209: Fix warnings in clang 10 build
After the last expression template update, some warnings popped up in the clang 10 build.

```
/usr/workspace/bramwell/gitspaces/serac/src/physics/../numerics/vector_expression.hpp:119:75: warning: operator '?:' has lower precedence than '+'; '+' will be evaluated first [-Wparentheses]
  const long long per_proc = (SIZE / num_procs) + (SIZE % num_procs != 0) ? 1 : 0;
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/usr/workspace/bramwell/gitspaces/serac/tests/expr_templates.cpp:62:3: note: in instantiation of function template specialization 'serac::evaluate<serac::internal::BinaryVectorExpr<mfem::Vector &, mfem::Vector &, std::plus<double> > >' requested here
  evaluate(lhs + rhs, expr_result, MPI_COMM_WORLD);
  ^
/usr/workspace/bramwell/gitspaces/serac/src/physics/../numerics/vector_expression.hpp:119:75: note: place parentheses around the '+' expression to silence this warning
  const long long per_proc = (SIZE / num_procs) + (SIZE % num_procs != 0) ? 1 : 0;
                                                                          ^
                             (                                           )
/usr/workspace/bramwell/gitspaces/serac/src/physics/../numerics/vector_expression.hpp:119:75: note: place parentheses around the '?:' expression to evaluate it first
  const long long per_proc = (SIZE / num_procs) + (SIZE % num_procs != 0) ? 1 : 0;
                                                                          ^
                                                  (                              )
```

### PR DESCRIPTION
**Pull request by joshessman-llnl**
The distribution of expression template evaluation isn't particularly useful outside the context of a distributed memory model, so this PR adds experimental support for using `mfem::HypreParVector` with expression templates.  The Sphinx docs have been updated to reflect this new functionality and its limitations.

Resolves #209

### CODE REVIEW

File: tests/benchmark_expr_templates.cpp [hunk 1]
```diff
@@ -34,6 +34,29 @@ static std::pair<mfem::DenseMatrix, mfem::Vector> sample_matvec(const int rows,
...
 }
 
+static auto build_partitioning(MPI_Comm comm, const int size)
+{
+  int num_procs = 0;
+  int rank      = 0;
+  MPI_Comm_size(comm, &num_procs);
+  MPI_Comm_rank(comm, &rank);
+  bool assumed_partition = HYPRE_AssumedPartitionCheck();
+  auto partitioning      = std::make_unique<int[]>(assumed_partition ? 2 : (num_procs + 1));
```
Comment (samuelpmishLLNL) [inline tests/benchmark_expr_templates.cpp:44]: At first glance, I'm not actually sure what `std::make_unique<int[]>(assumed_partition ? 2 : (num_procs + 1));` does. Does this need `std::unique_ptr`, or does `std::vector<int>` work?

File: tests/benchmark_expr_templates.cpp [hunk 2]
```diff
@@ -178,12 +201,38 @@ static void BM_large_expr_single_alloc_par_EXPR(benchmark::State& state)
...
+}
+
 BENCHMARK(BM_mixed_expr_MFEM)->RangeMultiplier(2)->Range(10, 10 << 10);
 BENCHMARK(BM_mixed_expr_EXPR)->RangeMultiplier(2)->Range(10, 10 << 10);
 BENCHMARK(BM_mixed_expr_single_alloc_EXPR)->RangeMultiplier(2)->Range(10, 10 << 10);
 BENCHMARK(BM_large_expr_MFEM)->RangeMultiplier(2)->Range(10, 10 << 10);
 BENCHMARK(BM_large_expr_single_alloc_EXPR)->RangeMultiplier(2)->Range(10, 10 << 10);
-BENCHMARK(BM_large_expr_single_alloc_par_EXPR)->RangeMultiplier(2)->Range(10, 10 << 10);
+
+// Too slow
```
Comment (samuelpmishLLNL) [inline tests/benchmark_expr_templates.cpp:233]: If we changed the large expr examples to use sparse matrices instead of dense, it could reduce the runtime of those tests and would be more representative of our calculations too.

**Review by samuelpmishLLNL — APPROVED** [review]

File: tests/benchmark_expr_templates.cpp (hunk 1 above)
Comment (joshessman-llnl) [reply tests/benchmark_expr_templates.cpp:44]: The conditional size check is because Hypre uses one of two schemes for partitioning, depending on how it was compiled.

The constructor for `HypreParVector` only needs a raw integer array.  `std::vector` + `v.data()` would work fine, but `unique_ptr` is slightly less overhead.

**Review by white238 — APPROVED** [review]

**Comment by joshessman-llnl** [comment]
LGTM
