### PR TITLE
Re-add Serac Cali macros

### LINKED ISSUE #1164: Caliper macros doubly defined
We now define a bunch of no-op Caliper macros when Serac is built without Caliper. It seems like LiDO does the same thing, and so when LiDO is built in codevelop mode, the compilation fails because the macros are doubly defined. Not sure if this is properly a Serac issue or a Caliper issue. I kindly request advice from @white238 or @chapman39 .

### PR DESCRIPTION
**Pull request by chapman39**
This PR re-adds the serac caliper wrapper macros.

The motivation is handling the case where benchmarking is disabled. In this case, we defined no-op versions of caliper macros, so marked code can still compile. However, if a Serac user (e.g. LiDO) does the same thing, we have a double define of macros, which results in a compiler error.

TODO
- [x] Re-add macros
- [x] Add comment mentioning motivation in profiling.hpp

Fixes #1164

### CODE REVIEW

**Review by tupek2 — APPROVED** [review]

**Review by btalamini — APPROVED** [review]

File: src/serac/infrastructure/profiling.hpp [hunk 1]
```diff
@@ -40,48 +40,60 @@
...
- * No-op macro in case Serac is not built with Caliper
+ * @def SERAC_MARK_END(id)
+ * Marks the end of a region Caliper profiling
  */
 
 /**
- * @def CALI_CXX_MARK_SCOPE(name)
- * No-op macro in case Serac is not built with Caliper
+ * @def SERAC_MARK_SCOPE(name)
+ * Marks a particular scope for Caliper profiling
```
Comment (white238) [inline src/serac/infrastructure/profiling.hpp]: Can you edit these to say "No-op macro when ENABLE_PROFILING is off"?

**Review by white238 — APPROVED** [review]
