### PR TITLE
Fix pulling exact commits for external repos

### LINKED ISSUE #239: Sundials doesn't link with clang
While sundials can link with gcc, it fails with clang due to a missing `libsundials_nvecmpiplusx.a` library.

```
[ 55%] Linking CXX executable ../../bin/serac
/usr/WS1/bramwell/gitspaces/serac_tpls/clang-10.0.0/mfem-4.1.0p1/lib/libmfem.a(sundials.o): In function `mfem::SundialsNVector::_SetNvecDataAndSize_(long)':
/usr/WS1/bramwell/gitspaces/serac_tpls/builds/spack-stage-mfem-4.1.0p1-2kqscwuxo3aomtzrqgelrtcelfn2eici/spack-src/linalg/sundials.cpp:154: undefined reference to `N_VGetLocalVector_MPIPlusX'
/usr/WS1/bramwell/gitspaces/serac_tpls/clang-10.0.0/mfem-4.1.0p1/lib/libmfem.a(sundials.o): In function `mfem::SundialsNVector::_SetDataAndSize_()':
/usr/WS1/bramwell/gitspaces/serac_tpls/builds/spack-stage-mfem-4.1.0p1-2kqscwuxo3aomtzrqgelrtcelfn2eici/spack-src/linalg/sundials.cpp:227: undefined reference to `N_VGetLocalVector_MPIPlusX'
/usr/WS1/bramwell/gitspaces/serac_tpls/clang-10.0.0/mfem-4.1.0p1/lib/libmfem.a(sundials.o): In function `~SundialsNVector':
/usr/WS1/bramwell/gitspaces/serac_tpls/builds/spack-stage-mfem-4.1.0p1-2kqscwuxo3aomtzrqgelrtcelfn2eici/spack-src/linalg/sundials.cpp:338: undefined reference to `N_VGetLocalVector_MPIPlusX'
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/drivers/CMakeFiles/serac_driver.dir/build.make:109: bin/serac] Error 1
make[1]: *** [CMakeFiles/Makefile2:2077: src/drivers/CMakeFiles/serac_driver.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
srun: error: rzgenie44: task 0: Exited with exit code 2
```

### PR DESCRIPTION
**Pull request by jamiebramwell**
It turns out we were not pulling the specific git commit for our external repos that are not at a version number. This fixes that as well as the Sundials test to reflect the new file structure.

Resolves https://github.com/LLNL/serac/issues/239 .

### CODE REVIEW

**Comment by jamiebramwell** [comment]
LGTM

File: tests/serac_dynamic_solver.cpp [hunk 1]
```diff
@@ -193,7 +193,7 @@ TEST(dynamic_solver, dyn_linesearch_solve)
   MPI_Barrier(MPI_COMM_WORLD);
 
   // Open the mesh
-  std::string mesh_file = std::string(SERAC_REPO_DIR) + "/data/beam-hex.mesh";
+  std::string mesh_file = std::string(SERAC_REPO_DIR) + "/data/meshes/beam-hex.mesh";
```
Comment (white238) [inline tests/serac_dynamic_solver.cpp:196]: NOOOO i missed one?!?! :shame:

Comment (jamiebramwell) [reply tests/serac_dynamic_solver.cpp:196]: This points at the fact we should be running our tests with optional dependencies.

File: scripts/uberenv/packages/axom/package.py [hunk 2]
```diff
@@ -55,7 +55,7 @@ class Axom(CMakePackage, CudaPackage):
     version('develop', branch='develop', submodules=True)
 
     # SERAC EDIT START
-    version('0.4.0p1', SHA='d74c5d971c62a2263efa438736440ff28620dc3d', submodules="True")
+    version('0.4.0p1', commit='d74c5d971c62a2263efa438736440ff28620dc3d', submodules="True")
```
Comment (white238) [inline scripts/uberenv/packages/axom/package.py:58]: Any time a version is changed but not bumped you need to do manually delete them from the mirror directory.

File: tests/serac_dynamic_solver.cpp (hunk 1 above)
Comment (joshessman-llnl) [reply tests/serac_dynamic_solver.cpp:196]: I think this one was on me - I think the sundials stuff went in after the inlet stuff.

**Review by white238 — APPROVED** [review]

File: tests/serac_dynamic_solver.cpp (hunk 1 above)
Comment (white238) [reply tests/serac_dynamic_solver.cpp:196]: meh.. you can blame me, very broken today. so tired. need breakfast burrito....

Comment (jamiebramwell) [reply tests/serac_dynamic_solver.cpp:196]: 🌯

**Review by joshessman-llnl — APPROVED** [review]
