### PR TITLE
Fix move assignment operator of finite element duals

### LINKED ISSUE #1352: Finite element dual assignment not working properly
https://github.com/LLNL/serac/blob/3ae05c23b51dad2b9256966def0cfe535bab1b4b/src/serac/physics/state/finite_element_dual.hpp#L58

Using this method to set a FiniteElementDual results in an incorrect output. Commenting it out such that the other assignment method is used results in the correct output.

### PR DESCRIPTION
**Pull request by btalamini**
Fixes #1352

### CODE REVIEW

File: src/serac/physics/state/tests/test_finite_element_dual.cpp [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+  std::string filename = SERAC_REPO_DIR "/data/meshes/beam-hex.mesh";
+  std::unique_ptr<mfem::ParMesh> mesh =
+      mesh::refineAndDistribute(buildMeshFromFile(filename), serial_refinement, parallel_refinement);
+  ASSERT_EQ(spatial_dim, mesh->SpaceDimension())
+      << "Test configured incorrectly. The variable spatial_dim must match the spatial dimension of the mesh.";
+
+  FiniteElementDual dual0(*mesh, H1<1>{}, "dual0");
+  dual0 = 1.0;
+
+  FiniteElementDual dual1(*mesh, H1<1>{}, "dual1");
```
Comment (tupek2) [inline src/serac/physics/state/tests/test_finite_element_dual.cpp]: why not FiniteElementDual dual1 = std::move(dual0); ?

**Review by tupek2 — APPROVED** [review]

File: src/serac/physics/state/tests/test_finite_element_dual.cpp (hunk 1 above)
Comment (btalamini) [reply src/serac/physics/state/tests/test_finite_element_dual.cpp]: no good reason. I can change it.

File: src/serac/physics/state/tests/test_finite_element_dual.cpp [hunk 2]
```diff
@@ -0,0 +1,53 @@
+// Copyright (c) 2019-2025, Lawrence Livermore National Security, LLC and
```
Comment (white238) [inline src/serac/physics/state/tests/test_finite_element_dual.cpp]:
```suggestion
// Copyright Lawrence Livermore National Security, LLC and
```

File: src/serac/physics/state/tests/test_finite_element_dual.cpp [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+}
+
+}  // namespace serac
+
+int main(int argc, char* argv[])
+{
+  ::testing::InitGoogleTest(&argc, argv);
+  serac::ApplicationManager applicationManager(argc, argv);
+  return RUN_ALL_TESTS();
+}
```
Comment (white238) [inline src/serac/physics/state/tests/test_finite_element_dual.cpp]:
```suggestion
}

```

**Review by white238 — APPROVED** [review]

File: src/serac/physics/state/tests/test_finite_element_dual.cpp (hunk 1 above)
Comment (btalamini) [reply src/serac/physics/state/tests/test_finite_element_dual.cpp]: changed
