### PR TITLE
Fix time-varying predicate-based component-wise Dirichlet boundary condition

### LINKED ISSUE #986: #7 functional_shape_derivatives failing occasionally
https://lc.llnl.gov/gitlab/smith/serac/-/jobs/1387779#L11812

```
/usr/WS1/bramwell/gl/builds/Nf6K8XKU/000/gitlab/smith/serac/src/serac/numerics/functional/tests/functional_shape_derivatives.cpp:329: Failure
The difference between mfem::InnerProduct(ones, dr) and 0.0 is 0.010675778755879772, which exceeds tolerance, where
mfem::InnerProduct(ones, dr) evaluates to 0.010675778755879772,
0.0 evaluates to 0, and
tolerance evaluates to 0.01.
```

### PR DESCRIPTION
**Pull request by jamiebramwell**
The function to set a Dirichlet boundary condition in the solid mechanics module did not previously compile. The issue was that the `setDisplacementBCsByDofList` method does not accept a component argument. This is now tested and fixed here, as well as used in one of @barreracruz 's test problems.

This also slightly loosens the tolerances on one of the tests that is now failing on Ubuntu 22 after the MFEM update.

It also loosens the tolerance of the `functional_shape_derivative` test as this was failing occasionally due to roundoff error.

Resolves https://github.com/LLNL/serac/issues/986

### CODE REVIEW

File: src/serac/physics/tests/solid.cpp [hunk 1]
```diff
@@ -136,8 +136,11 @@ void functional_solid_spatial_essential_bc()
   solid_solver.setMaterial(mat);
 
   // Set up
-  auto zero_vector   = [](const mfem::Vector&, mfem::Vector& u) { u = 0.0; };
-  auto zero_scalar   = [](const mfem::Vector&) { return 0.0; };
+  auto zero_vector = [](const mfem::Vector&, mfem::Vector& u) { u = 0.0; };
+
+  // We want to test both the scalar displacement functions including the time argument and the scalar displacement
+  // functions without
+  auto zero_scalar   = [](const mfem::Vector&, double) { return 0.0; };
```
Comment (samuelpmishLLNL) [inline src/serac/physics/tests/solid.cpp:143]: it might be worth only supporting the function signatures that include time, so there's half as many b.c. overloads to deal with

**Review by samuelpmishLLNL — APPROVED** [review]

File: src/serac/physics/tests/solid.cpp (hunk 1 above)
Comment (jamiebramwell) [reply src/serac/physics/tests/solid.cpp:143]: Agreed. I'll open this in an issue and complete it as a follow-on PR.

**Review by tupek2 — APPROVED** [review]
