### PR TITLE
Fix the doxygen warnings and turn on the CI check

### LINKED ISSUE #562: Turn on the doxygen checks with the appropriate fixes
👍 I can do this follow on PR

_Originally posted by @jamiebramwell in https://github.com/LLNL/serac/pull/556#discussion_r707793575_

### PR DESCRIPTION
**Pull request by jamiebramwell**
Resolves https://github.com/LLNL/serac/issues/562

### CODE REVIEW

**Review by white238 — APPROVED** [review]

File: src/serac/infrastructure/accelerator.hpp [hunk 1]
```diff
@@ -33,11 +33,20 @@
 #include <cuda_runtime.h>
 #else  //__CUDACC__
 /**
- * @brief Macro that toggles between decorating a function for host and device or noop's for non-accelated builds.
+ * @brief Macro that toggles between decorating a function for host_device or noop's for non-accelated builds.
```
Comment (samuelpmishLLNL) [inline src/serac/infrastructure/accelerator.hpp]:
```suggestion
 * @brief Macro that evaluates to `__host__ __device__` when compiling with nvcc and does nothing on a host compiler.
```

File: src/serac/infrastructure/accelerator.hpp [hunk 2]
```diff
@@ -33,11 +33,20 @@
...
  */
 #define SERAC_HOST_DEVICE
+/**
+ * @brief Macro that toggles between decorating a function for host or noop's for non-accelated builds.
+ */
 #define SERAC_HOST
+/**
+ * @brief Macro that toggles between decorating a function for device or noop's for non-accelated builds.
+ */
```
Comment (samuelpmishLLNL) [inline src/serac/infrastructure/accelerator.hpp]: the original wording makes it sound like it marks the function as being a no-op, rather than the macro itself doing nothing

I'm not sure what the right wording should be, this is consistent with the earlier suggestion:

Macro that evaluates to {`__host__`, `__device__`} when compiling with nvcc and does nothing on a host compiler

Comment (samuelpmishLLNL) [reply src/serac/infrastructure/accelerator.hpp]: also, for 1-liner doxygen comments, could we consider doing something like

```cpp
/// @brief lorem ipsum dolor si amet
#define SERAC_HOST
```

so that a 1-line function doesn't balloon into like 5 lines of code when adding doxygen comments?

Comment (jamiebramwell) [reply src/serac/infrastructure/accelerator.hpp]: I'm fine with this when appropriate. I honestly use the javadoc `/**` blocks because my vscode plugin can generate them automatically.

File: src/serac/physics/utilities/functional/functional.hpp [hunk 3]
```diff
@@ -85,9 +85,9 @@ inline int get_index(int i) { return (i >= 0) ? i : -1 - i; }
  * {sign, index} int32_t encoding)
  */
 struct SignedIndex {
-  int index;
-  int sign;
-      operator int() { return index; }
+  int index;                            ///< The index values
+  int sign;                             ///< The sign of the index
+      operator int() { return index; }  ///< () operator returning the index
```
Comment (samuelpmishLLNL) [inline src/serac/physics/utilities/functional/functional.hpp]:
```suggestion
      operator int() { return index; }  ///< implicit conversion to type `int`, returning index member variable

**Review by samuelpmishLLNL — APPROVED** [review]
